### ISSUE TITLE
Chore : /systeme-conception/images/consultation-profile-page-en.jpg is marked for deletion

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/systeme-conception#47] opened 2022-06-13 16:40 UTC
Hello, 

This file has been marked for deletion. Is there any additional context we should be aware of? FYI this file is also found in the EN repo.

**Comment by delisma** [comment] 2022-08-04 19:06
Duplicate of #46

**Closed by delisma** 2022-08-04 19:06 UTC
Labels: wontfix
